FROM postgis/postgis:14-3.4

ARG POSTGRES_DB=sensorthings
ARG POSTGRES_USER=sensorthings
ARG POSTGRES_PASSWORD=ChangeMe

ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER={POSTGRES_USER}
ENV POSTGRES_PASSWORD={POSTGRES_PASSWORD}

RUN useradd -r -m -U -d /opt/tomcat -s /bin/false tomcat

RUN apt-get update 

RUN apt-get install -y openjdk-11-jdk

RUN apt-get install -y wget

RUN wget -c https://downloads.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz

RUN apt-get install -y tar

RUN tar xf apache-tomcat-9.0.83.tar.gz -C /opt/tomcat

RUN ln -s /opt/tomcat/apache-tomcat-9.0.83 /opt/tomcat/updated

RUN chown -R tomcat: /opt/tomcat/*

RUN sh -c 'chmod +x /opt/tomcat/updated/bin/*.sh'

COPY tomcat.service /etc/systemd/system/tomcat.service

RUN apt-get -y install systemctl

RUN systemctl daemon-reload

RUN systemctl start tomcat

RUN ls

RUN wget https://repo1.maven.org/maven2/de/fraunhofer/iosb/ilt/FROST-Server/FROST-Server.HTTP/2.0.10/FROST-Server.HTTP-2.0.10.war
RUN wget https://repo1.maven.org/maven2/de/fraunhofer/iosb/ilt/FROST-Server/FROST-Server.HTTP/2.0.10/FROST-Server.HTTP-2.0.10-classes.jar
RUN wget https://repo1.maven.org/maven2/de/fraunhofer/iosb/ilt/FROST-Server/FROST-Server.HTTP/2.0.10/FROST-Server.HTTP-2.0.10-javadoc.jar
RUN wget https://repo1.maven.org/maven2/de/fraunhofer/iosb/ilt/FROST-Server/FROST-Server.HTTP/2.0.10/FROST-Server.HTTP-2.0.10-sources.jar
RUN wget https://repo1.maven.org/maven2/de/fraunhofer/iosb/ilt/FROST-Server/FROST-Server.HTTP/2.0.10/FROST-Server.HTTP-2.0.10.pom

RUN cp FROST-Server.HTTP-2.0.10.war /opt/tomcat/updated/webapps/
RUN cp FROST-Server.HTTP-2.0.10-classes.jar /opt/tomcat/updated/lib/
RUN cp FROST-Server.HTTP-2.0.10-javadoc.jar /opt/tomcat/updated/lib/
RUN cp FROST-Server.HTTP-2.0.10-sources.jar /opt/tomcat/updated/lib/
RUN cp FROST-Server.HTTP-2.0.10.pom /opt/tomcat/updated/lib/

RUN touch ${CATALINA_BASE}/bin/setenv.sh

# Add env variables to setenv.sh
RUN echo "export serviceRootUrl=http://localhost:8080/FROST-Server" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export plugins_multiDatastream.enable=false" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export http_cors_enable=true" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export http_cors_allowed_origins=*" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export persistence_db_driver=org.postgresql.Driver" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export persistence_db_url=jdbc:postgresql://localhost:5432/sensorthings" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export persistence_db_username=sensorthings" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export persistence_db_password=ChangeMe" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export wg=true" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export persistence_idGenerationMode=ServerAndClientGenerated" >> /opt/tomcat/updated/bin/setenv.sh

RUN echo "export defaultCount=false" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export defaultTop=100" >> /opt/tomcat/updated/bin/setenv.sh

RUN echo "export useAbsoluteNavigationLinks=true" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export countMode=FULL" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export extension_customLinks=true" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export extension_customLinks_recurseDepth=0" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export extension_filterDelete_enable=false" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export plugins_odata_enable=false" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export plugins_openApi_enable=true" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export resources_requests_cpu=300m" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export resources_requests_memory=900Mi" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export resources_limits_cpu=300m" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export resources_limits_memory=900Mi" >> /opt/tomcat/updated/bin/setenv.sh

RUN echo "export db_autoUpdate=true" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export alwaysOrderbyId=false" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export db_maximumConnection=10" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export db_maximumIdleConnection=10" >> /opt/tomcat/updated/bin/setenv.sh
RUN echo "export db_minimumIdleConnection=10" >> /opt/tomcat/updated/bin/setenv.sh