name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      registry: bikenow.vkw.tu-dresden.de
      image: ${{ github.repository }}
      branch: main
    secrets:
      NEXUS_DOCKER_PUB_USERNAME: ${{ secrets.NEXUS_DOCKER_PUB_USERNAME }}
      NEXUS_DOCKER_PUB_PASSWORD: ${{ secrets.NEXUS_DOCKER_PUB_PASSWORD }}
